spring:
  datasource:
    url: jdbc:informix-sqli://localhost:9088/syscdcv1:INFORMIXSERVER=informix
    username: ${IFX_DB_USER:informix}
    password: ${IFX_DB_PASS:in4mix}

logging.level.com.informix.stream.cdc: DEBUG